Widget fix
ASIDataScience/lens pull request #17
Opened 2017-10-16 17:09 UTC by shwinnn

Plotly interactive plots were no longer displayable in HTML widgets as of ipywidgets 6.0.0. Changed plots to use matplotlib allowing them to be displayed in ipython output widgets.

Fixes issue #6

2017-10-17 10:38 UTC, pbugnion commented
Following a discussion with Victor, the reason that `plot_pairdensity_mpl` and `plot_correlation_mpl` were introduced as new functions, rather than just replacing `plot_pairdensity` and `plot_correlation`, was to minimise work. If we decide to replace Plotly in the explorer (see issue #8 ), then we would just replace `plot_pairdensity` and `plot_correlation` with the `_mpl` versions.

2017-10-17 10:55 UTC, pbugnion requested changes
This should specify an ipywidgets lower bound of 6.0.0.

At the moment, in the pairwise density, if you try to choose the same column twice, the widget does not update. Maybe we should think of better UX around that?

I don't think this is a blocker here, but we should create a new issue for it.

2017-10-17 10:55 UTC, pbugnion commented on lens/plotting.py
> +        w /= np.sqrt(1.4)
Some pretty heavy use of magic numbers here. Why those numbers? What does this do?

2017-10-17 10:56 UTC, pbugnion commented
I've given this a fairly cursory review, but it looks good, modulo a couple of changes.

2017-10-23 14:28 UTC, pbugnion commented on lens/plotting.py
> +    # unless this exceeds 600 pixels.
Where did that 600 pixels number come from?

As a side-note, replacing `w` with `width_inches` would be a lot clearer.

2017-10-23 14:29 UTC, pbugnion commented on lens/plotting.py
>          w /= np.sqrt(1.4)
Why not just set `w = 10` here?

2017-10-23 15:20 UTC, pbugnion commented
I think this looks good.

2017-10-23 15:20 UTC, pbugnion approved these changes

2017-10-24 00:51 UTC, merged

2017-10-24 00:51 UTC, zblz commented
Thanks for the PR, @shwinnn!